update rating_system
set rating_mappings = 'QUESTION,-2,REJECTED;QUESTION,0,APPROVED;QUESTION,1,APPROVED;QUESTION,2,APPROVED;EXERCISE,0,REJECTED;EXERCISE,1,APPROVED;EXERCISE,2,APPROVED;EXERCISE,3,APPROVED;EXERCISE,4,APPROVED;EXERCISE,5,APPROVED;'
where id = 0;
